# Generated by Django 3.2.9 on 2021-12-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='comment',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
