# Generated by Django 3.2.9 on 2021-12-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_signature_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='comment',
            field=models.CharField(max_length=50),
        ),
    ]
